name       : tinyxml
version    : 2.6.2
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/tinyxml/tinyxml/2.6.2/tinyxml_2_6_2.tar.gz : 15bdfdcec58a7da30adc87ac2b078e4417dbe5392f3afb719f9ba6d062645593
license    : Zlib
summary    : Tiny XML Parser
description: |
    Tiny XML Parser
setup      : |
    patch -p1 < $pkgfiles/stl.patch
build      : |
    sed -i 's/TINYXML_USE_STL := NO/TINYXML_USE_STL := YES/g' Makefile
    sed -i 's/-Wall -Wno-unknown-pragmas -Wno-format -O3/-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -feliminate-unused-debug-types -Wno-error/g' Makefile
    %make
    g++ -fPIC "$CXXFLAGS" -shared -o "libtinyxml.so.0.2.6.2" -Wl,-soname,"libtinyxml.so.0" xmltest.o
install    : |
    install -d -m 0755 %installroot%/usr/{lib,include}
    install -m 0755 libtinyxml.so.0.2.6.2 %installroot%/usr/lib/
    install -m 0644 tinyxml.h tinystr.h %installroot%/usr/include
    install -Dm644 readme.txt %installroot%/usr/share/licenses/tinyxml/LICENSE
    install -Dm644 $pkgfiles/tinyxml.pc %installroot%/usr/lib/pkgconfig/tinyxml.pc
    ln -s %installroot%/usr/lib/libtinyxml.so.0.2.6.2 %installroot%/usr/lib/libtinyxml.so.0
    ln -s %installroot%/usr/lib/libtinyxml.so.0.2.6.2 %installroot%/usr/lib/libtinyxml.so
