name       : tinyxml
version    : 2.6.2
release    : 6
source     :
    - http://internode.dl.sourceforge.net/project/tinyxml/tinyxml/2.6.2/tinyxml_2_6_2.tar.gz : 15bdfdcec58a7da30adc87ac2b078e4417dbe5392f3afb719f9ba6d062645593
license    : Zlib
component  : system.utils
summary    : Tiny XML Parser
description: |
    Tiny XML Parser
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-Makefile-flags.patch
    %patch -p1 < $pkgfiles/0002-Force-define-STL-usage.patch
build      : |
    for i in tinyxml.cpp tinystr.cpp tinyxmlerror.cpp tinyxmlparser.cpp; do
        g++ $CXXFLAGS $LDFLAGS -fPIC -o $i.o -c $i
    done
    g++ -fPIC $CXXFLAGS -shared -o "libtinyxml.so.0.${version}" -Wl,-soname,"libtinyxml.so.0" *.cpp.o
install    : |
    install -d -m 0755 %installroot%/usr/include
    install -d -m 0755 %installroot%/%libdir%
    install -m 0755 libtinyxml.so.0.2.6.2 %installroot%/%libdir%/.
    install -m 0644 tinyxml.h tinystr.h %installroot%/usr/include
    install -Dm644 readme.txt %installroot%/usr/share/licenses/tinyxml/LICENSE
    install -Dm644 $pkgfiles/tinyxml.pc %installroot%/%libdir%/pkgconfig/tinyxml.pc
    ln -s libtinyxml.so.0.${version} %installroot%/%libdir%/libtinyxml.so.0
    ln -s libtinyxml.so.0.${version} %installroot%/%libdir%/libtinyxml.so
