name       : tinyxl
version    : 2.6.2
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/tinyxml/tinyxml/2.6.2/tinyxml_2_6_2.tar.gz : 15bdfdcec58a7da30adc87ac2b078e4417dbe5392f3afb719f9ba6d062645593
license    : Zlib
summary    : Tiny XML Parser
description: |
    Tiny XML Parser
setup      : |
    patch -p1 < $pkgfiles/stl.patch
build      : |
    sed -i 's/TINYXML_USE_STL := NO/TINYXML_USE_STL := YES/g' Makefile 
    %make
install    : |
    %make_install
